server:
  port: 9086

spring:
  application:
    name: balanceservice
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://microservices-eureka-service:8761/eureka/
  instance:
     hostname: balanceservice